/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InputDigitos {
        "alfanumerico": boolean;
        "desabilitaInputs": boolean;
        "digitosExternos": Array<string>;
        "tamanho": number;
        "tipoInput": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLInputDigitosElement extends Components.InputDigitos, HTMLStencilElement {
    }
    var HTMLInputDigitosElement: {
        prototype: HTMLInputDigitosElement;
        new (): HTMLInputDigitosElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "input-digitos": HTMLInputDigitosElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface InputDigitos {
        "alfanumerico"?: boolean;
        "desabilitaInputs"?: boolean;
        "digitosExternos"?: Array<string>;
        "onEnviaStringSaida"?: (event: CustomEvent<{digitado: boolean, string: string}>) => void;
        "tamanho"?: number;
        "tipoInput"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "input-digitos": InputDigitos;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "input-digitos": LocalJSX.InputDigitos & JSXBase.HTMLAttributes<HTMLInputDigitosElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
