/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TokenSms {
        "name": string;
        "tamanho": number;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTokenSmsElement extends Components.TokenSms, HTMLStencilElement {
    }
    var HTMLTokenSmsElement: {
        prototype: HTMLTokenSmsElement;
        new (): HTMLTokenSmsElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "token-sms": HTMLTokenSmsElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TokenSms {
        "name"?: string;
        "onEnviaTokenSaida"?: (event: CustomEvent<{digitado: boolean, token: string}>) => void;
        "tamanho"?: number;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "token-sms": TokenSms;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "token-sms": LocalJSX.TokenSms & JSXBase.HTMLAttributes<HTMLTokenSmsElement>;
        }
    }
}
